name: Run Smoke Tests

on:
  push:
    branches: [master]
    paths:
      - notion/**
      - smoke_tests/**

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: { python-version: '3.x' }

      - run: make dev-install
      - run: make install
      - run: make smoke-test
        env:
          NOTION_TOKEN_V2: ${{ secrets.NOTION_TOKEN_V2 }}
          NOTION_PAGE_URL: ${{ secrets.NOTION_PAGE_URL }}
